import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          <Image></Image>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About</a>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>Events</h1>
        {data.map((event) => (
          <a key={event.id} href="">
            <Image
              width={200}
              height={200}
              alt={event.title}
              src={event.image}
            />
            <h2>{event.title}</h2>
            <p>{event.description}</p>
          </a>
        ))}
      </main>
      <footer className={styles.footer}>
        <p>© 2023 - Aditi Polkam</p>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
